/*
 * Copyright (c) 2017.
 * author: daxingplay <daxingplay@gmail.com>
 */

module.exports = {
  control: [
    'TurnOn',
    'TurnOff',
    'SelectChannel',
    'AdjustUpChannel',
    'AdjustDownChannel',
    'AdjustUpVolume',
    'AdjustDownVolume',
    'SetVolume',
    'SetMute',
    'CancelMute',
    'Play',
    'Pause',
    'Continue',
    'Next',
    'Previous',
    'SetBrightness',
    'AdjustUpBrightness',
    'AdjustDownBrightness',
    'SetTemperature',
    'AdjustUpTemperature',
    'AdjustDownTemperature',
    'SetWindSpeed',
    'AdjustUpWindSpeed',
    'AdjustDownWindSpeed',
    'SetMode',
    'SetColor',
    'OpenFunction',
    'CloseFunction'
  ],
  query: [
    'Query',
    'QueryColor',
    'QueryPowerState',
    'QueryTemperature',
    'QueryHumidity',
    'QueryWindSpeed',
    'QueryBrightness',
    'QueryFog',
    'QueryMode',
    'QueryPM25',
    'QueryDirection',
    'QueryAngle'
  ],
  propertyMap: {
    powerstate: {
      from: 'state',
      values: ['on', 'off'],
    },
    color: {},
    temperature: {},
    windspeed: {},
    brightness: {},
    fog: {},
    humidity: {},
    'pm2.5': {},
    channel: {},
    number: {},
    direction: {
      values: ['left', 'right', 'forward', 'back', 'up', 'down'],
    },
    angle: {},
    anion: {
      values: ['on', 'off'],
    },
    effluent: {
      values: ['on', 'off'],
    },
    mode: {
      values: {
        auto: '自动模式',
        cold: '制冷模式',
        heat: '制热模式',
        ventilate: '通风模式',
        airsupply: '送风模式',
        dehumidification: '除湿模式',
        reading: '阅读模式',
        movie: '影院模式',
        sleep: '睡眠模式',
        live: '生活模式',
        manual: '手动模式',
        silent: '静音模式',
        energy: '省电模式',
        normalWind: '正常风模式',
        natureWind: '自然风模式',
        sleepWind: '睡眠风模式',
        quietWind: '静音风模式',
        comfortableWind: '舒适风模式',
        babyWind: '宝宝风模式',
        cottons: '棉织物模式',
        synthetics: '化纤模式',
        wool: '羊毛模式',
        hygiene: '除菌模式',
        drumClean: '筒清洁模式',
        silk: '丝绸模式',
        holiday: '假日模式',
        smart: '智能模式',
        music: '音乐模式',
        zeroGravity: '零重力模式',
        snoreStop: '止鼾模式',
        diffuse: '多人模式',
        swing: '摇摆模式',
        power: '强效模式'
      },
    },
    lefttime: {},
    remotestatus: {},
  },
};
